import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  transpilePackages: [
    "@zig/agent-audit",
    "@zig/agent-approvals",
    "@zig/agent-certification",
    "@zig/agent-control-tower",
    "@zig/agent-finops",
    "@zig/agent-alerting",
    "@zig/agent-chaos",
    "@zig/agent-costing",
    "@zig/agent-ingestion",
    "@zig/agent-ledger",
    "@zig/agent-registry",
    "@zig/agent-reliability",
    "@zig/agent-risk",
    "@zig/agent-scorecards",
    "@zig/agent-self-healing",
    "@zig/agent-telemetry",
    "@zig/model-telemetry",
    "@zig/supervisor-agents",
    "@zig/agents",
    "@zig/auth",
    "@zig/whitelabel",
    "@zig/billing",
    "@zig/automation",
    "@zig/integrations",
    "@zig/api",
    "@zig/frameworks",
    "@zig/agent-trigger-automation",
    "@zig/agent-runtime",
    "@zig/agent-governance",
    "@zig/agent-domain-intelligence",
    "@zig/agent-evidence-review",
    "@zig/agent-execution",
    "@zig/agent-learning-career",
    "@zig/governance-engine",
    "@zig/risks",
    "@zig/controls",
    "@zig/policies",
    "@zig/career-os",
    "@zig/certification-readiness",
    "@zig/adaptive-learning",
    "@zig/board-reporting",
    "@zig/evidence",
    "@zig/credentials",
    "@zig/assessment-engine",
    "@zig/learning-paths",
  ],
};

export default nextConfig;
