import type { NextConfig } from "next";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "../..");

const nextConfig: NextConfig = {
  turbopack: {
    root: repoRoot,
  },
  transpilePackages: [
    "@zig/types",
    "@zig/data-access",
    "@zig/services",
    "@zig/framework-engine",
    "@zig/governance-engine",
    "@zig/skills-graph",
    "@zig/adaptive-learning",
    "@zig/assessment-engine",
    "@zig/assessment-os",
    "@zig/practice-lab",
    "@zig/career-os",
    "@zig/career-readiness",
    "@zig/community-os",
    "@zig/community",
    "@zig/instructor-os",
    "@zig/learning-marketplace",
    "@zig/learning-analytics",
    "@zig/learning-runtime",
    "@zig/learning-os",
    "@zig/learning-agents",
    "@zig/student-twin",
    "@zig/apprenticeship",
    "@zig/capstones",
    "@zig/employment",
    "@zig/mentorship",
    "@zig/certification-journeys",
    "@zig/learning-kernel",
    "@zig/learning-orchestrator",
    "@zig/student-lifecycle",
    "@zig/learning-memory",
    "@zig/learning-paths",
    "@zig/certification-readiness",
    "@zig/employer-matching",
    "@zig/agent-performance",
    "@zig/learning-telemetry",
    "@zig/corporate-academies",
    "@zig/training-cloud",
    "@zig/university-platform",
    "@zig/cohorts",
    "@zig/mentorship-cloud",
    "@zig/employer-cloud",
    "@zig/workforce-development",
    "@zig/credentials",
    "@zig/training-marketplace",
    "@zig/workforce-analytics",
    "@zig/training-partners",
    "@zig/agents",
    "@zig/agent-memory",
    "@zig/approvals",
    "@zig/runtime-queue",
    "@zig/runtime-persistence",
    "@zig/runtime-telemetry",
    "@zig/enterprise-connectors",
    "@zig/marketplace",
    "@zig/services-marketplace",
    "@zig/partners",
    "@zig/whitelabel",
    "@zig/developer-platform",
    "@zig/knowledge-graph",
    "@zig/compliance-network",
    "@zig/compliance-protocol",
    "@zig/telemetry",
    "@zig/observability",
    "@zig/autonomous-evidence",
    "@zig/continuous-compliance",
    "@zig/autonomous-risk",
    "@zig/regulatory-intelligence",
    "@zig/digital-twin",
    "@zig/board-reporting",
    "@zig/copilot-runtime",
    "@zig/agent-workforce",
    "@zig/autonomous-workflows",
    "@zig/ai-governance",
    "@zig/autonomous-analytics",
    "@zig/billing",
    "@zig/automation",
    "@zig/frameworks",
    "@zig/controls",
    "@zig/risks",
    "@zig/evidence",
    "@zig/audits",
    "@zig/policies",
    "@zig/gaps",
    "@zig/ai",
    "@zig/imports",
    "@zig/exports",
    "@zig/integrations",
    "@zig/api",
    "@zig/webhooks",
    "@zig/ui",
  ],
};

export default nextConfig;
