import Link from "next/link";
import { DataTable, PageHeader, Section, StatCard } from "@zig/ui";
import { requireTenantContext } from "@/app/lib/auth";
import { labs } from "@/app/lib/mvp-data";

export default async function LabDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requireTenantContext();
  const { id } = await params;
  const lab = labs.find((item) => item.id === id) ?? labs[0];

  return (
    <>
      <PageHeader
        eyebrow="Lab Detail"
        title={lab.title}
        description={lab.scenario}
        actions={<Link className="rounded-md border border-[var(--zig-border)] px-3 py-2 text-sm" href={`/labs/session/${lab.id}`}>Start lab session</Link>}
      />
      <div className="grid gap-4 md:grid-cols-3">
        <StatCard label="Current Score" value={lab.score} detail="Rubric-weighted practice score." tone={lab.score >= 80 ? "healthy" : "neutral"} />
        <StatCard label="Tasks" value={lab.tasks.length} detail="Guided work items." />
        <StatCard label="Deliverables" value={lab.deliverables.length} detail="Artifacts generated by the session." />
      </div>
      <Section title="Tasks">
        <DataTable columns={["Task"]} empty="No tasks." rows={lab.tasks.map((task) => [task])} />
      </Section>
      <Section title="Expected Deliverables">
        <DataTable columns={["Deliverable"]} empty="No deliverables." rows={lab.deliverables.map((deliverable) => [deliverable])} />
      </Section>
      <Section title="Scoring Rubric">
        <DataTable columns={["Rubric Area"]} empty="No rubric." rows={lab.rubric.map((rubric) => [rubric])} />
      </Section>
    </>
  );
}
